export const moduleData = [
  {
    name: "Charging Stations",
    bestScenario: [
      "The best found configuration based on profit is characterized by 11 zones (max) with charging stations and 48 total number of poles.",
      "The best found configuration based on satisfied demand is characterized by 11 zones (max) with charging stations and 48 total number of poles.",
    ],
    variables: [
      {
        name: "Infrastructure Units",
        category: "Infrastructure",
        description:
          "Number of charging stations added to support growing electric vehicle requirements",
        cost: [
          { name: "Apr", value: 52000 },
          { name: "May", value: 63000 },
          { name: "Jun", value: 49000 },
          { name: "Jul", value: 82000 },
          { name: "Aug", value: 94000 },
          { name: "Sep", value: 102300 },
          { name: "Oct", value: 25000 },
        ],
        totalCost: 1020,
        selected: true,
      },
      {
        name: "Grid Upgrade Allocation",
        category: "Infrastructure",
        description:
          "Investment in upgrading electric grid infrastructure to handle additional charging load",
        cost: [
          { name: "Apr", value: 54000 },
          { name: "May", value: 68000 },
          { name: "Jun", value: 50000 },
          { name: "Jul", value: 82000 },
          { name: "Aug", value: 91000 },
          { name: "Sep", value: 102500 },
          { name: "Oct", value: 29000 },
        ],
        totalCost: 1070,
        selected: false,
      },
      {
        name: "Public Awareness Campaign",
        category: "Infrastructure",
        description:
          "Marketing efforts to promote electric vehicle adoption through outreach and education",
        cost: [
          { name: "Apr", value: 47000 },
          { name: "May", value: 54000 },
          { name: "Jun", value: 32000 },
          { name: "Jul", value: 82000 },
          { name: "Aug", value: 99000 },
          { name: "Sep", value: 105000 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 5000,
        selected: false,
      },
      {
        name: "Fleet Growth",
        category: "Operational",
        description:
          "Growth in vehicle fleet size required to fulfill increased transportation demand efficiently",
        cost: [
          { name: "Apr", value: 41000 },
          { name: "May", value: 48000 },
          { name: "Jun", value: 36000 },
          { name: "Jul", value: 95000 },
          { name: "Aug", value: 90000 },
          { name: "Sep", value: 103000 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 3000,
        selected: true,
      },
      {
        name: "Power Allocation",
        category: "Operational",
        description:
          "Energy units allocated specifically for charging across all operational charging stations",
        cost: [
          { name: "Apr", value: 44000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 30000 },
          { name: "Jul", value: 75000 },
          { name: "Aug", value: 81000 },
          { name: "Sep", value: 108000 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 9080,
        selected: true,
      },
      {
        name: "Maintenance Reserve",
        category: "Operational",
        description:
          "Reserve budget maintained regularly for equipment upkeep, repairs, and emergency breakdowns",
        cost: [
          { name: "Apr", value: 23000 },
          { name: "May", value: 46000 },
          { name: "Jun", value: 40000 },
          { name: "Jul", value: 95000 },
          { name: "Aug", value: 89000 },
          { name: "Sep", value: 34000 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 5340,
        selected: true,
      },
      {
        name: "Software Infrastructure",
        category: "Operational",
        description:
          "Development and maintenance of backend software managing routing, billing, and analytics",
        cost: [
          { name: "Apr", value: 41000 },
          { name: "May", value: 48000 },
          { name: "Jun", value: 36000 },
          { name: "Jul", value: 95000 },
          { name: "Aug", value: 90000 },
          { name: "Sep", value: 103000 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 6200,
        selected: false,
      },
      {
        name: "Carbon Offset Investments",
        category: "Sustainability",
        description:
          "Budget allocated for carbon reduction initiatives including tree planting and green credits",
        cost: [
          { name: "Apr", value: 41000 },
          { name: "May", value: 48000 },
          { name: "Jun", value: 36000 },
          { name: "Jul", value: 95000 },
          { name: "Aug", value: 90000 },
          { name: "Sep", value: 30300 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 7000,
        selected: false,
      },
      {
        name: "User Incentive Programs",
        category: "Sustainability",
        description:
          "Funds provided as user incentives to boost early adoption of green transport services",
        cost: [
          { name: "Apr", value: 52000 },
          { name: "May", value: 63000 },
          { name: "Jun", value: 49000 },
          { name: "Jul", value: 82000 },
          { name: "Aug", value: 98000 },
          { name: "Sep", value: 76230 },
          { name: "Oct", value: 25000 },
        ],
        totalCost: 4500,
        selected: false,
      },
      {
        name: "Battery Recycling Program",
        category: "Sustainability",
        description:
          "Resources dedicated to sustainable recycling of used EV batteries and components",
        cost: [
          { name: "Apr", value: 44000 },
          { name: "May", value: 68000 },
          { name: "Jun", value: 51000 },
          { name: "Jul", value: 82000 },
          { name: "Aug", value: 91000 },
          { name: "Sep", value: 47500 },
          { name: "Oct", value: 29000 },
        ],
        totalCost: 3900,
        selected: false,
      },
      {
        name: "Contingency Budget",
        category: "Financial Planning",
        description:
          "Allocated emergency reserve to handle unexpected expenses or delays in infrastructure deployment",
        cost: [
          { name: "Apr", value: 44000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 30000 },
          { name: "Jul", value: 75000 },
          { name: "Aug", value: 81000 },
          { name: "Sep", value: 90800 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 9500,
        selected: false,
      },
      {
        name: "Capital Expenditure Forecast",
        category: "Financial Planning",
        description:
          "Projected investments required for expansion including hardware, software, and real estate",
        cost: [
          { name: "Apr", value: 24000 },
          { name: "May", value: 32000 },
          { name: "Jun", value: 30000 },
          { name: "Jul", value: 65000 },
          { name: "Aug", value: 91000 },
          { name: "Sep", value: 108000 },
          { name: "Oct", value: 24000 },
        ],
        totalCost: 11200,
        selected: false,
      },
      {
        name: "Cost Optimization Initiatives",
        category: "Financial Planning",
        description:
          "Programs aimed at identifying inefficiencies and reducing recurring operational expenses",
        cost: [
          { name: "Apr", value: 12000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 24000 },
          { name: "Jul", value: 60000 },
          { name: "Aug", value: 48000 },
          { name: "Sep", value: 98700 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 6700,
        selected: false,
      },
    ],
  },

  {
    name: "Fleet Sizing",
    bestScenario: [
      "The optimal fleet configuration based on profitability includes 11 operational zones with charging infrastructure and a total of 48 charging poles.",
      "The optimal fleet configuration based on demand fulfillment includes 11 operational zones with charging infrastructure and a total of 48 charging poles.",
    ],

    variables: [
      {
        name: "Fleet Expansion",
        category: "Infrastructure",
        description:
          "Procurement and deployment of new electric vehicles to scale service coverage.",
        cost: [
          { name: "Apr", value: 49000 },
          { name: "May", value: 68000 },
          { name: "Jun", value: 27000 },
          { name: "Jul", value: 77000 },
          { name: "Aug", value: 59000 },
          { name: "Sep", value: 10300 },
          { name: "Oct", value: 51000 },
        ],
        totalCost: 1000,
        selected: true,
      },
      {
        name: "Depot Construction",
        category: "Infrastructure",
        description:
          "Infrastructure setup for fleet maintenance, charging, and vehicle storage.",
        cost: [
          { name: "Apr", value: 47000 },
          { name: "May", value: 54000 },
          { name: "Jun", value: 32000 },
          { name: "Jul", value: 82000 },
          { name: "Aug", value: 99000 },
          { name: "Sep", value: 50500 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 1750,
        selected: false,
      },
      {
        name: "Driver Training",
        category: "Operational",
        description:
          "Programs to train drivers in safety, navigation, and energy-efficient driving habits.",
        cost: [
          { name: "Apr", value: 12000 },
          { name: "May", value: 34000 },
          { name: "Jun", value: 26000 },
          { name: "Jul", value: 82000 },
          { name: "Aug", value: 99000 },
          { name: "Sep", value: 40500 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 7200,
        selected: true,
      },
      {
        name: "Vehicle Maintenance Plan",
        category: "Operational",
        description:
          "Scheduled and preventive maintenance for operational efficiency and uptime.",
        cost: [
          { name: "Apr", value: 23000 },
          { name: "May", value: 34000 },
          { name: "Jun", value: 10000 },
          { name: "Jul", value: 62000 },
          { name: "Aug", value: 99000 },
          { name: "Sep", value: 50000 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 8400,
        selected: true,
      },
      {
        name: "Fleet Monitoring System",
        category: "Operational",
        description:
          "Telematics-based real-time tracking and diagnostics for all fleet vehicles.",
        cost: [
          { name: "Apr", value: 97000 },
          { name: "May", value: 54000 },
          { name: "Jun", value: 32000 },
          { name: "Jul", value: 82000 },
          { name: "Aug", value: 99000 },
          { name: "Sep", value: 65000 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 6600,
        selected: false,
      },
      {
        name: "Battery Recycling",
        category: "Sustainability",
        description:
          "End-of-life battery recycling initiatives for reduced ecological impact.",
        cost: [
          { name: "Apr", value: 67000 },
          { name: "May", value: 55000 },
          { name: "Jun", value: 33000 },
          { name: "Jul", value: 80000 },
          { name: "Aug", value: 89000 },
          { name: "Sep", value: 42000 },
          { name: "Oct", value: 16000 },
        ],
        totalCost: 5200,
        selected: false,
      },
      {
        name: "Emission Reporting Tool",
        category: "Sustainability",
        description:
          "System to calculate and report carbon emissions saved across routes and trips.",
        cost: [
          { name: "Apr", value: 12431 },
          { name: "May", value: 40876 },
          { name: "Jun", value: 63000 },
          { name: "Jul", value: 32000 },
          { name: "Aug", value: 99000 },
          { name: "Sep", value: 15000 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 4300,
        selected: false,
      },
      {
        name: "Shared Mobility Promotion",
        category: "Sustainability",
        description:
          "Campaigns to encourage shared rides and reduce per-capita emissions.",
        cost: [
          { name: "Apr", value: 9000 },
          { name: "May", value: 31000 },
          { name: "Jun", value: 18000 },
          { name: "Jul", value: 65000 },
          { name: "Aug", value: 81000 },
          { name: "Sep", value: 54800 },
          { name: "Oct", value: 26000 },
        ],
        totalCost: 3900,
        selected: true,
      },
      {
        name: "Predictive Maintenance System",
        category: "Technology",
        description:
          "AI-based system to predict maintenance needs and prevent breakdowns.",
        cost: [
          { name: "Apr", value: 90000 },
          { name: "May", value: 31000 },
          { name: "Jun", value: 18000 },
          { name: "Jul", value: 65000 },
          { name: "Aug", value: 81000 },
          { name: "Sep", value: 54800 },
          { name: "Oct", value: 26000 },
        ],
        totalCost: 6100,
        selected: false,
      },
      {
        name: "Smart Route Optimization",
        category: "Technology",
        description:
          "Real-time route optimization system for fuel and time savings.",
        cost: [
          { name: "Apr", value: 47000 },
          { name: "May", value: 54000 },
          { name: "Jun", value: 32000 },
          { name: "Jul", value: 82000 },
          { name: "Aug", value: 99000 },
          { name: "Sep", value: 50500 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 7000,
        selected: true,
      },
      {
        name: "EV Subsidy Program",
        category: "Policy",
        description:
          "Subsidy for users adopting electric vehicles under government-backed policy.",
        cost: [
          { name: "Apr", value: 23000 },
          { name: "May", value: 34000 },
          { name: "Jun", value: 10000 },
          { name: "Jul", value: 62000 },
          { name: "Aug", value: 99000 },
          { name: "Sep", value: 50000 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 10500,
        selected: false,
      },
      {
        name: "Zero Emission Zone Incentive",
        category: "Policy",
        description:
          "Incentives for trips made within designated zero-emission zones.",
        cost: [
          { name: "Apr", value: 49000 },
          { name: "May", value: 68000 },
          { name: "Jun", value: 27000 },
          { name: "Jul", value: 77000 },
          { name: "Aug", value: 59000 },
          { name: "Sep", value: 10300 },
          { name: "Oct", value: 51000 },
        ],
        totalCost: 5600,
        selected: false,
      },
    ],
  },
  {
    name: "Parking",
    bestScenario: [
      "The best found configuration based on profit includes 11 parking zones (maximum) with parking stations and a total of 48 parking slots.",
      "The best found configuration based on satisfied demand includes 11 parking zones (maximum) with parking stations and a total of 48 parking slots.",
    ],

    variables: [
      {
        name: "Fleet Expansion",
        category: "Infrastructure",
        description:
          "Procurement and deployment of new electric vehicles to scale service coverage.",
        cost: [
          { name: "Apr", value: 47000 },
          { name: "May", value: 54000 },
          { name: "Jun", value: 32000 },
          { name: "Jul", value: 82000 },
          { name: "Aug", value: 99000 },
          { name: "Sep", value: 50500 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 14000,
        selected: true,
      },
      {
        name: "Depot Construction",
        category: "Infrastructure",
        description:
          "Infrastructure setup for fleet maintenance, charging, and vehicle storage.",
        cost: [
          { name: "Apr", value: 49000 },
          { name: "May", value: 68000 },
          { name: "Jun", value: 27000 },
          { name: "Jul", value: 77000 },
          { name: "Aug", value: 59000 },
          { name: "Sep", value: 10300 },
          { name: "Oct", value: 51000 },
        ],
        totalCost: 17500,
        selected: false,
      },
      {
        name: "Driver Training",
        category: "Operational",
        description:
          "Programs to train drivers in safety, navigation, and energy-efficient driving habits.",
        cost: [
          { name: "Apr", value: 12000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 24000 },
          { name: "Jul", value: 60000 },
          { name: "Aug", value: 48000 },
          { name: "Sep", value: 98700 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 7200,
        selected: true,
      },
      {
        name: "Vehicle Maintenance Plan",
        category: "Operational",
        description:
          "Scheduled and preventive maintenance for operational efficiency and uptime.",
        cost: [
          { name: "Apr", value: 12000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 24000 },
          { name: "Jul", value: 60000 },
          { name: "Aug", value: 48000 },
          { name: "Sep", value: 98700 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 8400,
        selected: true,
      },
      {
        name: "Fleet Monitoring System",
        category: "Operational",
        description:
          "Telematics-based real-time tracking and diagnostics for all fleet vehicles.",
        cost: [
          { name: "Apr", value: 12000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 24000 },
          { name: "Jul", value: 60000 },
          { name: "Aug", value: 48000 },
          { name: "Sep", value: 98700 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 6600,
        selected: false,
      },
      {
        name: "Battery Recycling",
        category: "Sustainability",
        description:
          "End-of-life battery recycling initiatives for reduced ecological impact.",
        cost: [
          { name: "Apr", value: 12000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 24000 },
          { name: "Jul", value: 60000 },
          { name: "Aug", value: 48000 },
          { name: "Sep", value: 98700 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 5200,
        selected: false,
      },
      {
        name: "Emission Reporting Tool",
        category: "Sustainability",
        description:
          "System to calculate and report carbon emissions saved across routes and trips.",
        cost: [
          { name: "Apr", value: 12000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 24000 },
          { name: "Jul", value: 60000 },
          { name: "Aug", value: 48000 },
          { name: "Sep", value: 98700 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 4300,
        selected: false,
      },
      {
        name: "Shared Mobility Promotion",
        category: "Sustainability",
        description:
          "Campaigns to encourage shared rides and reduce per-capita emissions.",
        cost: [
          { name: "Apr", value: 12000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 24000 },
          { name: "Jul", value: 60000 },
          { name: "Aug", value: 48000 },
          { name: "Sep", value: 98700 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 3900,
        selected: true,
      },
      {
        name: "Predictive Maintenance System",
        category: "Technology",
        description:
          "AI-based system to predict maintenance needs and prevent breakdowns.",
        cost: [
          { name: "Apr", value: 12000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 24000 },
          { name: "Jul", value: 60000 },
          { name: "Aug", value: 48000 },
          { name: "Sep", value: 98700 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 6100,
        selected: false,
      },
      {
        name: "Smart Route Optimization",
        category: "Technology",
        description:
          "Real-time route optimization system for fuel and time savings.",
        cost: [
          { name: "Apr", value: 12000 },
          { name: "May", value: 36000 },
          { name: "Jun", value: 24000 },
          { name: "Jul", value: 60000 },
          { name: "Aug", value: 48000 },
          { name: "Sep", value: 98700 },
          { name: "Oct", value: 20000 },
        ],
        totalCost: 7000,
        selected: true,
      },
      {
        name: "EV Subsidy Program",
        category: "Policy",
        description:
          "Subsidy for users adopting electric vehicles under government-backed policy.",
        cost: [
          { name: "Apr", value: 49000 },
          { name: "May", value: 68000 },
          { name: "Jun", value: 27000 },
          { name: "Jul", value: 77000 },
          { name: "Aug", value: 59000 },
          { name: "Sep", value: 10300 },
          { name: "Oct", value: 51000 },
        ],
        totalCost: 10500,
        selected: false,
      },
      {
        name: "Zero Emission Zone Incentive",
        category: "Policy",
        description:
          "Incentives for trips made within designated zero-emission zones.",
        cost: [
          { name: "Apr", value: 49000 },
          { name: "May", value: 68000 },
          { name: "Jun", value: 27000 },
          { name: "Jul", value: 77000 },
          { name: "Aug", value: 59000 },
          { name: "Sep", value: 10300 },
          { name: "Oct", value: 51000 },
        ],
        totalCost: 5600,
        selected: false,
      },
    ],
  },
];
